version: '3.6'

services:
  coroner:
    build:
      dockerfile: Dockerfile
      context: .
    image: mythern/coroner
    restart: unless-stopped
    networks:
      - default
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.overflow.rule=Host(`coroner.ulv.no`)"
      - "traefik.http.routers.overflow.tls=true"
      - "traefik.http.routers.overflow.tls.certresolver=le"

# Define the Traefik network for auto detection from forward proxy
networks:
  traefik:
    external: true
